// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.jump.account.base.protobuf;

public final class AccountOuterClass {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_jump_account_base_protobuf_AccountMessage_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_jump_account_base_protobuf_AccountMessage_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\raccount.proto\022\036com.jump.account.base.p" +
                        "rotobuf\"m\n\016AccountMessage\022\n\n\002id\030\001 \001(\005\022\014\n" +
                        "\004name\030\002 \001(\t\022\017\n\007message\030\003 \001(\t\022\013\n\003url\030\004 \001(" +
                        "\t\022\021\n\tuser_name\030\005 \001(\t\022\020\n\010password\030\006 \001(\014B\023" +
                        "B\021AccountOuterClassb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_com_jump_account_base_protobuf_AccountMessage_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_jump_account_base_protobuf_AccountMessage_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_jump_account_base_protobuf_AccountMessage_descriptor,
                new java.lang.String[]{"Id", "Name", "Message", "Url", "UserName", "Password",});
    }

    private AccountOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface AccountMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.jump.account.base.protobuf.AccountMessage)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 id = 1;</code>
         */
        int getId();

        /**
         * <code>string name = 2;</code>
         */
        java.lang.String getName();

        /**
         * <code>string name = 2;</code>
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>string message = 3;</code>
         */
        java.lang.String getMessage();

        /**
         * <code>string message = 3;</code>
         */
        com.google.protobuf.ByteString
        getMessageBytes();

        /**
         * <code>string url = 4;</code>
         */
        java.lang.String getUrl();

        /**
         * <code>string url = 4;</code>
         */
        com.google.protobuf.ByteString
        getUrlBytes();

        /**
         * <code>string user_name = 5;</code>
         */
        java.lang.String getUserName();

        /**
         * <code>string user_name = 5;</code>
         */
        com.google.protobuf.ByteString
        getUserNameBytes();

        /**
         * <code>bytes password = 6;</code>
         */
        com.google.protobuf.ByteString getPassword();
    }

    /**
     * Protobuf type {@code com.jump.account.base.protobuf.AccountMessage}
     */
    public static final class AccountMessage extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.jump.account.base.protobuf.AccountMessage)
            AccountMessageOrBuilder {
        public static final int ID_FIELD_NUMBER = 1;
        public static final int NAME_FIELD_NUMBER = 2;
        public static final int MESSAGE_FIELD_NUMBER = 3;
        public static final int URL_FIELD_NUMBER = 4;
        public static final int USER_NAME_FIELD_NUMBER = 5;
        public static final int PASSWORD_FIELD_NUMBER = 6;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:com.jump.account.base.protobuf.AccountMessage)
        private static final com.jump.account.base.protobuf.AccountOuterClass.AccountMessage DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<AccountMessage>
                PARSER = new com.google.protobuf.AbstractParser<AccountMessage>() {
            public AccountMessage parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new AccountMessage(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new com.jump.account.base.protobuf.AccountOuterClass.AccountMessage();
        }

        private int id_;
        private volatile java.lang.Object name_;
        private volatile java.lang.Object message_;
        private volatile java.lang.Object url_;
        private volatile java.lang.Object userName_;
        private com.google.protobuf.ByteString password_;
        private byte memoizedIsInitialized = -1;

        // Use AccountMessage.newBuilder() to construct.
        private AccountMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private AccountMessage() {
            id_ = 0;
            name_ = "";
            message_ = "";
            url_ = "";
            userName_ = "";
            password_ = com.google.protobuf.ByteString.EMPTY;
        }

        private AccountMessage(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            id_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();

                            message_ = s;
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();

                            url_ = s;
                            break;
                        }
                        case 42: {
                            java.lang.String s = input.readStringRequireUtf8();

                            userName_ = s;
                            break;
                        }
                        case 50: {

                            password_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.jump.account.base.protobuf.AccountOuterClass.internal_static_com_jump_account_base_protobuf_AccountMessage_descriptor;
        }

        public static com.jump.account.base.protobuf.AccountOuterClass.AccountMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.jump.account.base.protobuf.AccountOuterClass.AccountMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.jump.account.base.protobuf.AccountOuterClass.AccountMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.jump.account.base.protobuf.AccountOuterClass.AccountMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.jump.account.base.protobuf.AccountOuterClass.AccountMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.jump.account.base.protobuf.AccountOuterClass.AccountMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.jump.account.base.protobuf.AccountOuterClass.AccountMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.jump.account.base.protobuf.AccountOuterClass.AccountMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.jump.account.base.protobuf.AccountOuterClass.AccountMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.jump.account.base.protobuf.AccountOuterClass.AccountMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.jump.account.base.protobuf.AccountOuterClass.AccountMessage prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static com.jump.account.base.protobuf.AccountOuterClass.AccountMessage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<AccountMessage> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.jump.account.base.protobuf.AccountOuterClass.internal_static_com_jump_account_base_protobuf_AccountMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.jump.account.base.protobuf.AccountOuterClass.AccountMessage.class, com.jump.account.base.protobuf.AccountOuterClass.AccountMessage.Builder.class);
        }

        /**
         * <code>int32 id = 1;</code>
         */
        public int getId() {
            return id_;
        }

        /**
         * <code>string name = 2;</code>
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <code>string name = 2;</code>
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string message = 3;</code>
         */
        public java.lang.String getMessage() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                message_ = s;
                return s;
            }
        }

        /**
         * <code>string message = 3;</code>
         */
        public com.google.protobuf.ByteString
        getMessageBytes() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                message_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string url = 4;</code>
         */
        public java.lang.String getUrl() {
            java.lang.Object ref = url_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                url_ = s;
                return s;
            }
        }

        /**
         * <code>string url = 4;</code>
         */
        public com.google.protobuf.ByteString
        getUrlBytes() {
            java.lang.Object ref = url_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                url_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string user_name = 5;</code>
         */
        public java.lang.String getUserName() {
            java.lang.Object ref = userName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                userName_ = s;
                return s;
            }
        }

        /**
         * <code>string user_name = 5;</code>
         */
        public com.google.protobuf.ByteString
        getUserNameBytes() {
            java.lang.Object ref = userName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                userName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>bytes password = 6;</code>
         */
        public com.google.protobuf.ByteString getPassword() {
            return password_;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (id_ != 0) {
                output.writeInt32(1, id_);
            }
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
            }
            if (!getMessageBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
            }
            if (!getUrlBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, url_);
            }
            if (!getUserNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, userName_);
            }
            if (!password_.isEmpty()) {
                output.writeBytes(6, password_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (id_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, id_);
            }
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
            }
            if (!getMessageBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
            }
            if (!getUrlBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, url_);
            }
            if (!getUserNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, userName_);
            }
            if (!password_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(6, password_);
            }
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.jump.account.base.protobuf.AccountOuterClass.AccountMessage)) {
                return super.equals(obj);
            }
            com.jump.account.base.protobuf.AccountOuterClass.AccountMessage other = (com.jump.account.base.protobuf.AccountOuterClass.AccountMessage) obj;

            boolean result = true;
            result = result && (getId()
                    == other.getId());
            result = result && getName()
                    .equals(other.getName());
            result = result && getMessage()
                    .equals(other.getMessage());
            result = result && getUrl()
                    .equals(other.getUrl());
            result = result && getUserName()
                    .equals(other.getUserName());
            result = result && getPassword()
                    .equals(other.getPassword());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + getId();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
            hash = (53 * hash) + getMessage().hashCode();
            hash = (37 * hash) + URL_FIELD_NUMBER;
            hash = (53 * hash) + getUrl().hashCode();
            hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
            hash = (53 * hash) + getUserName().hashCode();
            hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
            hash = (53 * hash) + getPassword().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<AccountMessage> getParserForType() {
            return PARSER;
        }

        public com.jump.account.base.protobuf.AccountOuterClass.AccountMessage getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code com.jump.account.base.protobuf.AccountMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.jump.account.base.protobuf.AccountMessage)
                com.jump.account.base.protobuf.AccountOuterClass.AccountMessageOrBuilder {
            private int id_;
            private java.lang.Object name_ = "";
            private java.lang.Object message_ = "";
            private java.lang.Object url_ = "";
            private java.lang.Object userName_ = "";
            private com.google.protobuf.ByteString password_ = com.google.protobuf.ByteString.EMPTY;

            // Construct using com.jump.account.base.protobuf.AccountOuterClass.AccountMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.jump.account.base.protobuf.AccountOuterClass.internal_static_com_jump_account_base_protobuf_AccountMessage_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.jump.account.base.protobuf.AccountOuterClass.internal_static_com_jump_account_base_protobuf_AccountMessage_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.jump.account.base.protobuf.AccountOuterClass.AccountMessage.class, com.jump.account.base.protobuf.AccountOuterClass.AccountMessage.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                id_ = 0;

                name_ = "";

                message_ = "";

                url_ = "";

                userName_ = "";

                password_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.jump.account.base.protobuf.AccountOuterClass.internal_static_com_jump_account_base_protobuf_AccountMessage_descriptor;
            }

            public com.jump.account.base.protobuf.AccountOuterClass.AccountMessage getDefaultInstanceForType() {
                return com.jump.account.base.protobuf.AccountOuterClass.AccountMessage.getDefaultInstance();
            }

            public com.jump.account.base.protobuf.AccountOuterClass.AccountMessage build() {
                com.jump.account.base.protobuf.AccountOuterClass.AccountMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.jump.account.base.protobuf.AccountOuterClass.AccountMessage buildPartial() {
                com.jump.account.base.protobuf.AccountOuterClass.AccountMessage result = new com.jump.account.base.protobuf.AccountOuterClass.AccountMessage(this);
                result.id_ = id_;
                result.name_ = name_;
                result.message_ = message_;
                result.url_ = url_;
                result.userName_ = userName_;
                result.password_ = password_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.jump.account.base.protobuf.AccountOuterClass.AccountMessage) {
                    return mergeFrom((com.jump.account.base.protobuf.AccountOuterClass.AccountMessage) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.jump.account.base.protobuf.AccountOuterClass.AccountMessage other) {
                if (other == com.jump.account.base.protobuf.AccountOuterClass.AccountMessage.getDefaultInstance())
                    return this;
                if (other.getId() != 0) {
                    setId(other.getId());
                }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (!other.getMessage().isEmpty()) {
                    message_ = other.message_;
                    onChanged();
                }
                if (!other.getUrl().isEmpty()) {
                    url_ = other.url_;
                    onChanged();
                }
                if (!other.getUserName().isEmpty()) {
                    userName_ = other.userName_;
                    onChanged();
                }
                if (other.getPassword() != com.google.protobuf.ByteString.EMPTY) {
                    setPassword(other.getPassword());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.jump.account.base.protobuf.AccountOuterClass.AccountMessage parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.jump.account.base.protobuf.AccountOuterClass.AccountMessage) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>int32 id = 1;</code>
             */
            public int getId() {
                return id_;
            }

            /**
             * <code>int32 id = 1;</code>
             */
            public Builder setId(int value) {

                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 id = 1;</code>
             */
            public Builder clearId() {

                id_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>string name = 2;</code>
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string name = 2;</code>
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string name = 2;</code>
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string name = 2;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string name = 2;</code>
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>string message = 3;</code>
             */
            public java.lang.String getMessage() {
                java.lang.Object ref = message_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    message_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string message = 3;</code>
             */
            public Builder setMessage(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                message_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string message = 3;</code>
             */
            public com.google.protobuf.ByteString
            getMessageBytes() {
                java.lang.Object ref = message_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    message_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string message = 3;</code>
             */
            public Builder setMessageBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                message_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string message = 3;</code>
             */
            public Builder clearMessage() {

                message_ = getDefaultInstance().getMessage();
                onChanged();
                return this;
            }

            /**
             * <code>string url = 4;</code>
             */
            public java.lang.String getUrl() {
                java.lang.Object ref = url_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    url_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string url = 4;</code>
             */
            public Builder setUrl(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                url_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string url = 4;</code>
             */
            public com.google.protobuf.ByteString
            getUrlBytes() {
                java.lang.Object ref = url_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    url_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string url = 4;</code>
             */
            public Builder setUrlBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                url_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string url = 4;</code>
             */
            public Builder clearUrl() {

                url_ = getDefaultInstance().getUrl();
                onChanged();
                return this;
            }

            /**
             * <code>string user_name = 5;</code>
             */
            public java.lang.String getUserName() {
                java.lang.Object ref = userName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    userName_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string user_name = 5;</code>
             */
            public Builder setUserName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                userName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string user_name = 5;</code>
             */
            public com.google.protobuf.ByteString
            getUserNameBytes() {
                java.lang.Object ref = userName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    userName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string user_name = 5;</code>
             */
            public Builder setUserNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                userName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string user_name = 5;</code>
             */
            public Builder clearUserName() {

                userName_ = getDefaultInstance().getUserName();
                onChanged();
                return this;
            }

            /**
             * <code>bytes password = 6;</code>
             */
            public com.google.protobuf.ByteString getPassword() {
                return password_;
            }

            /**
             * <code>bytes password = 6;</code>
             */
            public Builder setPassword(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                password_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bytes password = 6;</code>
             */
            public Builder clearPassword() {

                password_ = getDefaultInstance().getPassword();
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:com.jump.account.base.protobuf.AccountMessage)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
